/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author lianp
 */
public class CriarTarefa extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CriarTarefa.class.getName());

    private InicioTarefas telaTarefas;
    private int linhaEdicao = -1;

    // Construtor vazio (necessário para o NetBeans abrir no Design)
    public CriarTarefa() {
        initComponents();
    }

    // Construtor usado quando cria nova tarefa
    public CriarTarefa(InicioTarefas telaTarefas) {
        initComponents();
        this.telaTarefas = telaTarefas;
    }

    // Construtor usado para editar tarefa já existente
    public CriarTarefa(InicioTarefas telaTarefas, int linha, String titulo, String descricao, String materia, String prioridade, String dataEntrega) {
        initComponents();
        this.telaTarefas = telaTarefas;
        this.linhaEdicao = linha;

        jTextFieldTitulo.setText(titulo);
        jTextFieldDescrição.setText(descricao);
        jTextFieldMatéria.setText(materia);
        jComboBoxPrioridade.setSelectedItem(prioridade);
        jTextFieldDataEntrega.setText(dataEntrega);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextFieldDataEntrega = new javax.swing.JTextField();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldDescrição = new javax.swing.JTextField();
        jComboBoxPrioridade = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMatéria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        setMaximumSize(new java.awt.Dimension(1440, 810));
        setMinimumSize(new java.awt.Dimension(1440, 810));
        setPreferredSize(new java.awt.Dimension(1440, 810));

        jScrollPane2.setMaximumSize(new java.awt.Dimension(1440, 810));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(1440, 810));
        jScrollPane2.setOpaque(false);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(1440, 810));

        jLayeredPane1.setBackground(new java.awt.Color(102, 102, 255));
        jLayeredPane1.setMaximumSize(new java.awt.Dimension(1440, 810));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(1440, 810));
        jLayeredPane1.setName(""); // NOI18N
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1440, 810));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 700, 230, 40));

        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 680, 90, 70));

        jTextFieldDataEntrega.setBackground(new java.awt.Color(31, 80, 20));
        jTextFieldDataEntrega.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jTextFieldDataEntrega.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldDataEntrega.setText("Digite a data precista de conclusão/");
        jTextFieldDataEntrega.setBorder(null);
        jLayeredPane1.add(jTextFieldDataEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 620, 510, 40));

        jTextFieldTitulo.setBackground(new java.awt.Color(31, 80, 20));
        jTextFieldTitulo.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jTextFieldTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTitulo.setText("Digite o Titulo/");
        jTextFieldTitulo.setBorder(null);
        jLayeredPane1.add(jTextFieldTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 510, 30));

        jTextFieldDescrição.setBackground(new java.awt.Color(31, 80, 20));
        jTextFieldDescrição.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jTextFieldDescrição.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldDescrição.setText("Digite a Descrição/");
        jTextFieldDescrição.setBorder(null);
        jLayeredPane1.add(jTextFieldDescrição, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 510, 30));

        jComboBoxPrioridade.setBackground(new java.awt.Color(31, 80, 20));
        jComboBoxPrioridade.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jComboBoxPrioridade.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxPrioridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o nível de Prioridade", "Alta", "Média", "Baixa" }));
        jComboBoxPrioridade.setBorder(null);
        jLayeredPane1.add(jComboBoxPrioridade, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 510, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/voltar back.png"))); // NOI18N
        jLayeredPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 670, 100, -1));

        jTextFieldMatéria.setBackground(new java.awt.Color(31, 80, 20));
        jTextFieldMatéria.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jTextFieldMatéria.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldMatéria.setText("Digite a Matéria/");
        jTextFieldMatéria.setBorder(null);
        jLayeredPane1.add(jTextFieldMatéria, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 510, 30));

        jLabel1.setBackground(new java.awt.Color(204, 0, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Inicio (11) (1).png"))); // NOI18N
        jLabel1.setName(""); // NOI18N
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 810));

        jScrollPane2.setViewportView(jLayeredPane1);
        jLayeredPane1.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String titulo = jTextFieldTitulo.getText();
    String descricao = jTextFieldDescrição.getText();
    String materia = jTextFieldMatéria.getText();
    String prioridade = jComboBoxPrioridade.getSelectedItem().toString();
    String dataEntrega = jTextFieldDataEntrega.getText();

    // Validação simples (opcional, mas recomendado)
    if (titulo.isEmpty() || descricao.isEmpty() || materia.isEmpty() || 
        prioridade.equals("Selecione o nível de Prioridade") || dataEntrega.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
        return;
    }

    // Se for uma nova tarefa
    if (linhaEdicao == -1) {
        telaTarefas.adicionarTarefa(titulo, descricao, materia, prioridade, dataEntrega);
    } else {
        telaTarefas.atualizarTarefa(linhaEdicao, titulo, descricao, materia, prioridade, dataEntrega);
    }

    // Mostra novamente a tela de tarefas e fecha a atual
    telaTarefas.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxPrioridade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldDataEntrega;
    private javax.swing.JTextField jTextFieldDescrição;
    private javax.swing.JTextField jTextFieldMatéria;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
