/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.Tarefa;
import Model.Usuario;
import controller.TarefaController;

import java.time.LocalDate;

import javax.swing.JOptionPane;
/**
 *
 * @author lianp
 */
public class EditarTarefa extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarTarefa.class.getName());
    private Usuario usuarioLogado;
    private TarefaController controller;
    private InicioTarefas telaTarefas;
    private int linhaEdicao = -1;
    private int idTarefa;


    // Construtor vazio (necessário para o NetBeans abrir no Design)
    public EditarTarefa(
        InicioTarefas telaTarefas,
        int idTarefa,
        String titulo,
        String descricao,
        String materia,
        String prioridade,
        String dataEntrega,
        Usuario usuario
    )   {
    
        initComponents();
    
        this.telaTarefas = telaTarefas;
        this.idTarefa = idTarefa;
        this.usuarioLogado = usuario;
        this.controller = new TarefaController();

        jTextFieldTituloEditar.setText(titulo);
        jTextFieldDescriçãoEditar.setText(descricao);
        jTextFieldMatériaEditar.setText(materia);
        jComboBoxPrioridadeEditar.setSelectedItem(prioridade);
        jTextFieldDataEntregaEditar.setText(dataEntrega);
    }


    // Construtor usado quando cria nova tarefa
    public EditarTarefa(InicioTarefas telaTarefas, Usuario usuario
    //InicioTarefas telaTarefas
    ) 
    {
     /*   initComponents();
        this.telaTarefas = telaTarefas;*/
         initComponents();
        this.telaTarefas = telaTarefas;
        this.usuarioLogado = usuario;
        this.controller = new TarefaController();

    }

    // Construtor usado para editar tarefa já existente
        public EditarTarefa(InicioTarefas telaTarefas, Usuario usuario, Tarefa tarefa) {
        initComponents();
        this.telaTarefas = telaTarefas;
        this.usuarioLogado = usuario;
        this.controller = new TarefaController();
        this.idTarefa = tarefa.getIdTarefa();

        jTextFieldTituloEditar.setText(tarefa.getTitulo());
        jTextFieldDescriçãoEditar.setText(tarefa.getDescricao());
        jTextFieldMatériaEditar.setText(tarefa.getMateria());
        jComboBoxPrioridadeEditar.setSelectedItem(tarefa.getPrioridade());
        jTextFieldDataEntregaEditar.setText(tarefa.getDataEntrega().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2Editar = new javax.swing.JScrollPane();
        jLayeredPane1Editar = new javax.swing.JLayeredPane();
        jButton1Editar = new javax.swing.JButton();
        jButton2Editar = new javax.swing.JButton();
        jTextFieldDataEntregaEditar = new javax.swing.JTextField();
        jTextFieldTituloEditar = new javax.swing.JTextField();
        jTextFieldDescriçãoEditar = new javax.swing.JTextField();
        jComboBoxPrioridadeEditar = new javax.swing.JComboBox<>();
        jTextFieldMatériaEditar = new javax.swing.JTextField();
        jLabel1Editar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        setMinimumSize(new java.awt.Dimension(1440, 810));

        jScrollPane2Editar.setMaximumSize(new java.awt.Dimension(1440, 810));
        jScrollPane2Editar.setMinimumSize(new java.awt.Dimension(1440, 810));
        jScrollPane2Editar.setOpaque(false);
        jScrollPane2Editar.setPreferredSize(new java.awt.Dimension(1440, 810));

        jLayeredPane1Editar.setBackground(new java.awt.Color(102, 102, 255));
        jLayeredPane1Editar.setMaximumSize(new java.awt.Dimension(1440, 810));
        jLayeredPane1Editar.setMinimumSize(new java.awt.Dimension(1440, 810));
        jLayeredPane1Editar.setName(""); // NOI18N
        jLayeredPane1Editar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1Editar.setBorder(null);
        jButton1Editar.setContentAreaFilled(false);
        jButton1Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1EditarActionPerformed(evt);
            }
        });
        jLayeredPane1Editar.add(jButton1Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 700, 250, 70));

        jButton2Editar.setContentAreaFilled(false);
        jButton2Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2EditarActionPerformed(evt);
            }
        });
        jLayeredPane1Editar.add(jButton2Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 690, 110, 90));

        jTextFieldDataEntregaEditar.setBackground(new java.awt.Color(31, 80, 20));
        jTextFieldDataEntregaEditar.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jTextFieldDataEntregaEditar.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldDataEntregaEditar.setText("Digite a data precista de conclusão/");
        jTextFieldDataEntregaEditar.setBorder(null);
        jTextFieldDataEntregaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataEntregaEditarActionPerformed(evt);
            }
        });
        jLayeredPane1Editar.add(jTextFieldDataEntregaEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 630, 520, 40));

        jTextFieldTituloEditar.setBackground(new java.awt.Color(31, 80, 20));
        jTextFieldTituloEditar.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jTextFieldTituloEditar.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTituloEditar.setText("Digite o Titulo/");
        jTextFieldTituloEditar.setBorder(null);
        jLayeredPane1Editar.add(jTextFieldTituloEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 520, 40));

        jTextFieldDescriçãoEditar.setBackground(new java.awt.Color(31, 80, 20));
        jTextFieldDescriçãoEditar.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jTextFieldDescriçãoEditar.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldDescriçãoEditar.setText("Digite a Descrição/");
        jTextFieldDescriçãoEditar.setBorder(null);
        jLayeredPane1Editar.add(jTextFieldDescriçãoEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 520, 40));

        jComboBoxPrioridadeEditar.setBackground(new java.awt.Color(31, 80, 20));
        jComboBoxPrioridadeEditar.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jComboBoxPrioridadeEditar.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxPrioridadeEditar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o nível de Prioridade", "Alta", "Média", "Baixa" }));
        jComboBoxPrioridadeEditar.setBorder(null);
        jLayeredPane1Editar.add(jComboBoxPrioridadeEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 510, 40));

        jTextFieldMatériaEditar.setBackground(new java.awt.Color(31, 80, 20));
        jTextFieldMatériaEditar.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jTextFieldMatériaEditar.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldMatériaEditar.setText("Digite a Matéria/");
        jTextFieldMatériaEditar.setBorder(null);
        jLayeredPane1Editar.add(jTextFieldMatériaEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 520, 40));

        jLabel1Editar.setBackground(new java.awt.Color(204, 0, 255));
        jLabel1Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/TelaEditarTarefa.png"))); // NOI18N
        jLabel1Editar.setName(""); // NOI18N
        jLayeredPane1Editar.add(jLabel1Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 840));

        jScrollPane2Editar.setViewportView(jLayeredPane1Editar);
        jLayeredPane1Editar.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jScrollPane2Editar, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1EditarActionPerformed
    String titulo = jTextFieldTituloEditar.getText();
    String descricao = jTextFieldDescriçãoEditar.getText();
    String materia = jTextFieldMatériaEditar.getText();
    String prioridade = jComboBoxPrioridadeEditar.getSelectedItem().toString();
    String dataTexto = jTextFieldDataEntregaEditar.getText();

    // Validação simples (opcional, mas recomendado)
    if (titulo.isEmpty() || materia.isEmpty() || 
        prioridade.equals("Selecione o nível de Prioridade") || dataTexto.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
        return;
    }

    LocalDate dataEntrega;

    try {
        dataEntrega = LocalDate.parse(dataTexto);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Data inválida. Use AAAA-MM-DD.");
        return;
    }
    
        // 🔹 CRIA A TAREFA
    Tarefa tarefa = new Tarefa();
    tarefa.setIdTarefa(this.idTarefa);
    tarefa.setTitulo(titulo);
    tarefa.setDescricao(descricao);
    tarefa.setMateria(materia);
    tarefa.setPrioridade(prioridade);
    tarefa.setDataEntrega(dataEntrega);
    tarefa.setUsuario(usuarioLogado);

    boolean sucesso = controller.editar(tarefa);
    
    if (sucesso) {
        JOptionPane.showMessageDialog(this, "Tarefa atualizada com sucesso!");
        this.dispose();
        new InicioTarefas(usuarioLogado).setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "Erro ao salvar tarefa.");
    }

    }//GEN-LAST:event_jButton1EditarActionPerformed

    private void jButton2EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2EditarActionPerformed
    this.dispose();
    telaTarefas.setVisible(true);
    telaTarefas.toFront();
    telaTarefas.requestFocus();
    
    }//GEN-LAST:event_jButton2EditarActionPerformed

    private void jTextFieldDataEntregaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataEntregaEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataEntregaEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Editar;
    private javax.swing.JButton jButton2Editar;
    private javax.swing.JComboBox<String> jComboBoxPrioridadeEditar;
    private javax.swing.JLabel jLabel1Editar;
    private javax.swing.JLayeredPane jLayeredPane1Editar;
    private javax.swing.JScrollPane jScrollPane2Editar;
    private javax.swing.JTextField jTextFieldDataEntregaEditar;
    private javax.swing.JTextField jTextFieldDescriçãoEditar;
    private javax.swing.JTextField jTextFieldMatériaEditar;
    private javax.swing.JTextField jTextFieldTituloEditar;
    // End of variables declaration//GEN-END:variables
}
