/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Usuario;
import controller.TarefaController;
import Model.Tarefa;
import java.util.List;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lianp
 */
public class InicioTarefas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InicioTarefas.class.getName());

    private void carregarTarefasDoBanco() {
    DefaultTableModel modelo = (DefaultTableModel) jTableTarefas.getModel();
    modelo.setRowCount(0); // limpa tabela antes de preencher

    try {
        List<Tarefa> lista = controller.listarPorUsuario(usuarioLogado);
        for (Tarefa t : lista) {
            // correspondendo às colunas: Título, Descrição, Matéria, Prioridade, Data Início, Data Entrega, Editar, Excluir
            modelo.addRow(new Object[]{
                t.getTitulo(),
                t.getDescricao(),
                t.getMateria(),
                t.getPrioridade(),
                LocalDate.now().toString(),            // Data Início (pode ajustar se você tiver no model)
                t.getDataEntrega() != null ? t.getDataEntrega() : "",
                "Editar",
                "Excluir"
            });
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erro ao carregar tarefas: " + e.getMessage());
    }
}
    public InicioTarefas() {
        initComponents();
    }
    /**
     * Creates new form InicioTarefas
     */
 /*   public InicioTarefas() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTableTarefas.getModel();

        jTableTarefas.getColumn("Editar").setCellRenderer(new ButtonRenderer("Editar"));
        jTableTarefas.getColumn("Editar").setCellEditor(new ButtonEditor(new javax.swing.JCheckBox(), jTableTarefas, "editar"));

        jTableTarefas.getColumn("Excluir").setCellRenderer(new ButtonRenderer("Excluir"));
        jTableTarefas.getColumn("Excluir").setCellEditor(new ButtonEditor(new javax.swing.JCheckBox(), jTableTarefas, "excluir"));
    }*/
    
private Usuario usuarioLogado;
private TarefaController controller;

public InicioTarefas(Usuario usuario) {
    initComponents();
    this.usuarioLogado = usuario;
    this.controller = new TarefaController();
    

    // Configuração da tabela
    jTableTarefas.getColumn("Editar").setCellRenderer(new ButtonRenderer("Editar"));
    jTableTarefas.getColumn("Editar").setCellEditor(new ButtonEditor(new javax.swing.JCheckBox(), jTableTarefas, "editar"));

    jTableTarefas.getColumn("Excluir").setCellRenderer(new ButtonRenderer("Excluir"));
    jTableTarefas.getColumn("Excluir").setCellEditor(new ButtonEditor(new javax.swing.JCheckBox(), jTableTarefas, "excluir"));

    // Carrega tarefas do banco
    carregarTarefasDoBanco();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTarefas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableTarefas.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jTableTarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Descrição", "Matéria", "Prioridade", "Data Início", "Data Entrega", "Editar", "Excluir"
            }
        ));
        jScrollPane1.setViewportView(jTableTarefas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 1380, 560));

        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 160, 200, 40));

        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 250, 60));

        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 20, 120, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/perfil correct.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 20, 140, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Inicio (12) (3).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CriarTarefa criarTarefa = new CriarTarefa(this, usuarioLogado);
        criarTarefa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Pomodoro timer = new Pomodoro();
        timer.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Perfil perfil = new Perfil ();
        perfil.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    JOptionPane.showMessageDialog(null, 
        "Esta tela não pode ser iniciada sem login.");
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTarefas;
    // End of variables declaration//GEN-END:variables
    
    public void adicionarTarefa(String titulo, String descricao, String materia, String prioridade, String dataEntrega) {
        DefaultTableModel modelo = (DefaultTableModel) jTableTarefas.getModel();
        modelo.addRow(new Object[]{titulo, descricao, materia, prioridade, LocalDate.now(), dataEntrega});
    }

    // Atualiza tarefa existente
    public void atualizarTarefa(int linha, String titulo, String descricao, String materia, String prioridade, String dataEntrega) {
        DefaultTableModel modelo = (DefaultTableModel) jTableTarefas.getModel();
        modelo.setValueAt(titulo, linha, 0);
        modelo.setValueAt(descricao, linha, 1);
        modelo.setValueAt(materia, linha, 2);
        modelo.setValueAt(prioridade, linha, 3);
        modelo.setValueAt(LocalDate.now(), linha, 4);
        modelo.setValueAt(dataEntrega, linha, 5);
    }

    // Abre tela de edição
    private void editarTarefa(int linha) {
        DefaultTableModel modelo = (DefaultTableModel) jTableTarefas.getModel();

        String titulo = modelo.getValueAt(linha, 0).toString();
        String descricao = modelo.getValueAt(linha, 1).toString();
        String materia = modelo.getValueAt(linha, 2).toString();
        String prioridade = modelo.getValueAt(linha, 3).toString();
        String dataEntrega = modelo.getValueAt(linha, 5).toString();

        CriarTarefa editarTela = new CriarTarefa(this, linha, titulo, descricao, materia, prioridade, dataEntrega);
        editarTela.setVisible(true);
        this.setVisible(false);
    }

    // Exclui tarefa
    private void excluirTarefa(int linha) {
        DefaultTableModel modelo = (DefaultTableModel) jTableTarefas.getModel();
        modelo.removeRow(linha);
        JOptionPane.showMessageDialog(this, "Tarefa excluída!");
    }

    // Renderer (botão na célula)
    class ButtonRenderer extends javax.swing.JButton implements javax.swing.table.TableCellRenderer {
        public ButtonRenderer(String texto) {
            setText(texto);
            setOpaque(true);
        }

        @Override
        public java.awt.Component getTableCellRendererComponent(
                javax.swing.JTable table, Object value, boolean isSelected,
                boolean hasFocus, int row, int column) {
            return this;
        }
    }

    // Editor (ação dos botões)
    class ButtonEditor extends javax.swing.DefaultCellEditor {
        private String label;
        private boolean clicked;
        private int linha;
        private javax.swing.JTable tabela;
        private String tipo;

        public ButtonEditor(javax.swing.JCheckBox checkBox, javax.swing.JTable tabela, String tipo) {
            super(checkBox);
            this.tabela = tabela;
            this.tipo = tipo;
        }

        @Override
        public java.awt.Component getTableCellEditorComponent(
                javax.swing.JTable table, Object value, boolean isSelected, int row, int column) {
            linha = row;
            label = (tipo.equals("editar")) ? "Editar" : "Excluir";
            clicked = true;
            javax.swing.JButton btn = new javax.swing.JButton(label);
            btn.addActionListener(e -> {
                if (tipo.equals("editar")) editarTarefa(linha);
                else excluirTarefa(linha);
            });
            return btn;
        }

        @Override
        public Object getCellEditorValue() {
            clicked = false;
            return label;
        }

        @Override
        public boolean stopCellEditing() {
            clicked = false;
            return super.stopCellEditing();
        }
    }
}

