package View;

import Model.Usuario;
import javax.swing.JOptionPane;
import controller.UsuarioController;


/**
 *
 * @author lianp
 */
public class Perfil extends javax.swing.JFrame {
    private InicioTarefas telaTarefas;
    private Usuario usuario;
    private UsuarioController controller;

public Perfil(InicioTarefas telaTarefas, Usuario usuario) {


    if (usuario == null) {
        JOptionPane.showMessageDialog(this,
                "Esta tela não pode ser aberta sem login.");
        dispose();
        return;
    }
        initComponents();
        this.telaTarefas = telaTarefas;
        this.usuario = usuario;
        this.controller = new UsuarioController();

        preencherCampos();
    }

    private void preencherCampos() {
        jtxtNome.setText(usuario.getNome());
        jtxtEmail.setText(usuario.getEmail());
        jtxtSenha.setText(usuario.getSenha());
        jtxtData.setText(usuario.getDataNascimento().toString());

        // Campos já começam editáveis
        jtxtNome.setEditable(true);
        jtxtEmail.setEditable(true);
        jtxtSenha.setEditable(true);

        // Data continua apenas visual
        jtxtData.setEditable(false);
    }
    
    private void liberarCampos() {
        jtxtNome.setEditable(true);
        jtxtEmail.setEditable(true);
        jtxtSenha.setEditable(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton3 = new javax.swing.JButton();
        jtxtEmail = new javax.swing.JTextField();
        jtxtData = new javax.swing.JTextField();
        jtxtNome = new javax.swing.JTextField();
        jtxtSenha = new javax.swing.JTextField();
        jbtnEditar = new javax.swing.JButton();
        jbtnExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        setMinimumSize(new java.awt.Dimension(1440, 810));

        jScrollPane2.setMaximumSize(new java.awt.Dimension(1440, 810));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(1440, 810));
        jScrollPane2.setOpaque(false);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(1440, 810));

        jLayeredPane1.setBackground(new java.awt.Color(102, 102, 255));
        jLayeredPane1.setMaximumSize(new java.awt.Dimension(1440, 810));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(1440, 810));
        jLayeredPane1.setName(""); // NOI18N
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 100, 80));

        jtxtEmail.setBackground(new java.awt.Color(31, 80, 20));
        jtxtEmail.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jtxtEmail.setForeground(new java.awt.Color(255, 255, 255));
        jtxtEmail.setBorder(null);
        jLayeredPane1.add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 520, 50));

        jtxtData.setBackground(new java.awt.Color(31, 80, 20));
        jtxtData.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jtxtData.setForeground(new java.awt.Color(255, 255, 255));
        jtxtData.setBorder(null);
        jtxtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDataActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jtxtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, 530, 50));

        jtxtNome.setBackground(new java.awt.Color(31, 80, 20));
        jtxtNome.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jtxtNome.setForeground(new java.awt.Color(255, 255, 255));
        jtxtNome.setBorder(null);
        jLayeredPane1.add(jtxtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 520, 40));

        jtxtSenha.setBackground(new java.awt.Color(31, 80, 20));
        jtxtSenha.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jtxtSenha.setForeground(new java.awt.Color(255, 255, 255));
        jtxtSenha.setBorder(null);
        jLayeredPane1.add(jtxtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 530, 40));

        jbtnEditar.setContentAreaFilled(false);
        jbtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditarActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jbtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 680, 220, 60));

        jbtnExcluir.setContentAreaFilled(false);
        jbtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExcluirActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jbtnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 680, 240, 60));

        jLabel1.setBackground(new java.awt.Color(204, 0, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/TelaPerfil.png"))); // NOI18N
        jLabel1.setName(""); // NOI18N
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 810));

        jScrollPane2.setViewportView(jLayeredPane1);
        jLayeredPane1.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            this.dispose();
            telaTarefas.setVisible(true); // volta para a tela anterior
            telaTarefas.toFront();        // traz para frente
            telaTarefas.requestFocus();
            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtxtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDataActionPerformed

    private void jbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarActionPerformed
String nome = jtxtNome.getText().trim();
        String email = jtxtEmail.getText().trim();
        String senha = jtxtSenha.getText().trim();

        if (nome.isEmpty() || email.isEmpty() || senha.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Preencha todos os campos.");
            return;
        }

        Usuario u = new Usuario();
        u.setIdUsuario(usuario.getIdUsuario());
        u.setNome(nome);
        u.setEmail(email);
        u.setSenha(senha);
        u.setDataNascimento(usuario.getDataNascimento());

        boolean sucesso = controller.editar(u);

if (sucesso) {
    JOptionPane.showMessageDialog(this,
            "Dados atualizados com sucesso!");

    this.usuario = u;

    if (telaTarefas != null) {
        telaTarefas.setUsuarioLogado(u);
    }}
else {
            JOptionPane.showMessageDialog(this,
                    "Erro ao atualizar os dados.");
        }
    }//GEN-LAST:event_jbtnEditarActionPerformed
    
    
    private void jbtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExcluirActionPerformed
        int opcao = JOptionPane.showConfirmDialog(
                this,
                "Tem certeza que deseja excluir sua conta?\nEssa ação não pode ser desfeita.",
                "Excluir conta",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (opcao != JOptionPane.YES_OPTION) return;

        boolean sucesso = controller.excluir(usuario.getIdUsuario());

        if (sucesso) {
            JOptionPane.showMessageDialog(this,
                    "Conta excluída com sucesso.");
            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Erro ao excluir conta.");
        }
    }//GEN-LAST:event_jbtnExcluirActionPerformed

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnExcluir;
    private javax.swing.JTextField jtxtData;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtNome;
    private javax.swing.JTextField jtxtSenha;
    // End of variables declaration//GEN-END:variables
}
